openapi: 3.0.2
info:
  title: Flowchem - devices
  description: Flowchem is a python library to control a variety of instruments commonly
    found in chemistry labs.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 0.1.0a3
paths:
  /vici-valve/injection-valve/position/:
    get:
      tags:
        - vici-valve/injection-valve
        - vici-valve/injection-valve
      summary: Get Position
      description: "Get current valve position."
      operationId: run_vici-valve_injection-valve_run_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
  /vici-valve/injection-valve/position:
    put:
      tags:
        - vici-valve
        - vici-valve
      summary: Set Position
      description: "Move valve to position, which connects named ports"
      operationId: run_vici-valve_injection-valve_run_put
      parameters:
        - required: true
          schema:
            title: connect
            type: string
            default: ''
          name: connect
          in: query
        - required: true
          schema:
            title: disconnect
            type: string
            default: ''
          name: disconnect
          in: query
        - required: false
          schema:
            title: ambiguous_switching
            type: boolean | string
            default: false
          name: ambiguous_switching
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
  /vici-valve/injection-valve/connections/:
    get:
      tags:
        - vici-valve
        - vici-valve
      summary: Get Position
      description: "Get the list of all available positions for this valve.
        This mainly has informative purpose"
      operationId: run_vici-valve_injection-valve_run_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
            - type: boolean
            - type: tuple
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
