openapi: 3.0.2
info:
  title: Flowchem - flowchem_config
  description: Flowchem is a python library to control a variety of instruments commonly
    found in chemistry labs.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 0.1.0a3
paths:
  /cvc-1/pressure-control/:
    get:
      tags:
      - cvc-1
      - cvc-1
      summary: Get Metadata
      description: Return metadata.
      operationId: get_metadata_cvc_1_pressure_control__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentInfo'
  /cvc-1/pressure-control/pressure:
    get:
      tags:
      - cvc-1
      - cvc-1
      summary: Get Pressure
      description: Return pressure in mbar.
      operationId: get_pressure_cvc_1_pressure_control_pressure_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    put:
      tags:
      - cvc-1
      - cvc-1
      summary: Set Pressure
      description: Set the target pressure to the given string in natural language.
      operationId: set_pressure_cvc_1_pressure_control_pressure_put
      parameters:
      - required: true
        schema:
          title: Pressure
          type: string
        name: pressure
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /cvc-1/pressure-control/power-on:
    put:
      tags:
      - cvc-1
      - cvc-1
      summary: Power On
      description: Turn on temperature control.
      operationId: power_on_cvc_1_pressure_control_power_on_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /cvc-1/pressure-control/power-off:
    put:
      tags:
      - cvc-1
      - cvc-1
      summary: Power Off
      description: Turn off temperature control.
      operationId: power_off_cvc_1_pressure_control_power_off_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /cvc-1/pressure-control/target-reached:
    get:
      tags:
      - cvc-1
      - cvc-1
      summary: Is Target Reached
      description: Return True if the set temperature target has been reached.
      operationId: is_target_reached_cvc_1_pressure_control_target_reached_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /cvc-1/pressure-control/status:
    put:
      tags:
      - cvc-1
      - cvc-1
      summary: Status
      description: Get process status reply.
      operationId: status_cvc_1_pressure_control_status_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessStatus'
components:
  schemas:
    ComponentInfo:
      title: ComponentInfo
      required:
      - hw_device
      type: object
      properties:
        hw_device:
          $ref: '#/components/schemas/DeviceInfo'
        name:
          title: Name
          type: string
          default: ''
        owl_subclass_of:
          title: Owl Subclass Of
          type: string
          default: http://purl.obolibrary.org/obo/OBI_0000968
      description: Metadata associated with flowchem components.
    DeviceInfo:
      title: DeviceInfo
      required:
      - authors
      - maintainers
      - manufacturer
      - model
      type: object
      properties:
        authors:
          title: Authors
          type: array
          items:
            $ref: '#/components/schemas/Person'
        maintainers:
          title: Maintainers
          type: array
          items:
            $ref: '#/components/schemas/Person'
        manufacturer:
          title: Manufacturer
          type: string
        model:
          title: Model
          type: string
        additional_info:
          title: Additional Info
          type: object
          default: {}
        backend:
          title: Backend
          type: string
          default: flowchem v. 0.1.0a3
        serial_number:
          title: Serial Number
          type: string
          default: unknown
        version:
          title: Version
          type: string
          default: ''
      description: Metadata associated with hardware devices.
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Person:
      title: Person
      required:
      - name
      - email
      type: object
      properties:
        name:
          title: Name
          type: string
        email:
          title: Email
          type: string
    ProcessStatus:
      title: ProcessStatus
      required:
      - is_pump_on
      - is_inline_valve_open
      - is_coolant_valve_open
      - is_venting_valve_open
      - control
      - state
      type: object
      properties:
        is_pump_on:
          title: Is Pump On
          type: boolean
        is_inline_valve_open:
          title: Is Inline Valve Open
          type: boolean
        is_coolant_valve_open:
          title: Is Coolant Valve Open
          type: boolean
        is_venting_valve_open:
          title: Is Venting Valve Open
          type: boolean
        control:
          $ref: '#/components/schemas/PumpControlMode'
        state:
          $ref: '#/components/schemas/PumpState'
    PumpControlMode:
      title: PumpControlMode
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      type: integer
      description: An enumeration.
    PumpState:
      title: PumpState
      enum:
      - 0
      - 1
      - 2
      - 3
      type: integer
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
