openapi: 3.1.0
info:
  title: 'Flowchem - '
  description: Flowchem is a library to control instruments and devices commonly found
    in chemistry labs via an interoperable web API.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0a3
paths:
  /my-knauervalve/:
    get:
      tags:
      - my-knauervalve
      summary: Get Device Info
      operationId: get_device_info_fake_device__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInfo'
  /my-knauervalve/injection-valve/:
    get:
      tags:
      - my-knauervalve
      - my-knauervalve
      summary: Get Component Info
      description: "Retrieve the component's metadata.\n\nThis endpoint provides information\
        \ about the component, such as its name and associated hardware device.\n\n\
        Returns:\n--------\nComponentInfo\n    Metadata about the component."
      operationId: get_component_info_fake_device_injection_valve__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentInfo'
  /my-knauervalve/injection-valve/position:
    get:
      tags:
      - my-knauervalve
      - my-knauervalve
      summary: Get Position
      description: "Get the current valve position.\n\nReturns:\n    tuple: The current\
        \ position of the valve."
      operationId: get_position_fake_device_injection_valve_position_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                prefixItems:
                - type: array
                  items: {}
                - type: array
                  items: {}
                minItems: 2
                maxItems: 2
                title: Response Get Position Fake Device Injection Valve Position
                  Get
    put:
      tags:
      - my-knauervalve
      - my-knauervalve
      summary: Set Position
      description: "Move the valve to the position that connects the specified ports.\n\
        \nArgs:\n    connect: Ports to connect.\n    disconnect: Ports to disconnect.\n\
        \    ambiguous_switching: If True, allows ambiguous switching."
      operationId: set_position_fake_device_injection_valve_position_put
      parameters:
      - name: ambiguous_switching
        in: query
        required: false
        schema:
          type: boolean
          default: false
          title: Ambiguous Switching
      requestBody:
        content:
          multipart/form-data:
            schema:
              allOf:
              - $ref: '#/components/schemas/Body_set_position_fake_device_injection_valve_position_put'
              title: Body
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /my-knauervalve/injection-valve/connections:
    get:
      tags:
      - my-knauervalve
      - my-knauervalve
      summary: Connections
      description: "Get the list of all available positions for this valve.\n\nReturns:\n\
        \    ValveInfo: The ValveInfo object containing ports and positions."
      operationId: connections_fake_device_injection_valve_connections_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValveInfo'
  /my-knauervalve/injection-valve/monitor_position:
    get:
      tags:
      - my-knauervalve
      - my-knauervalve
      summary: Get Monitor Position
      description: "Get the current valve position.\n\nReturns:\n    str: The current\
        \ position (LOAD or INJECT)."
      operationId: get_monitor_position_fake_device_injection_valve_monitor_position_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Get Monitor Position Fake Device Injection Valve Monitor
                  Position Get
    put:
      tags:
      - my-knauervalve
      - my-knauervalve
      summary: Set Monitor Position
      description: "Set the valve to a specified position.\n\nArgs:\n    position\
        \ (str): The desired position (LOAD or INJECT).\n\nReturns:\n    str: The\
        \ response from the hardware device."
      operationId: set_monitor_position_fake_device_injection_valve_monitor_position_put
      parameters:
      - name: position
        in: query
        required: true
        schema:
          type: string
          title: Position
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_set_position_fake_device_injection_valve_position_put:
      properties:
        connect:
          anyOf:
          - type: string
          - items: {}
            type: array
          title: Connect
          default: ''
        disconnect:
          anyOf:
          - type: string
          - items: {}
            type: array
          title: Disconnect
          default: ''
      type: object
      title: Body_set_position_fake_device_injection_valve_position_put
    ComponentInfo:
      properties:
        name:
          type: string
          title: Name
          default: ''
        parent_device:
          type: string
          title: Parent Device
          default: ''
        type:
          type: string
          title: Type
          default: ''
        owl_subclass_of:
          items:
            type: string
          type: array
          title: Owl Subclass Of
          default:
          - http://purl.obolibrary.org/obo/OBI_0000968
      type: object
      title: ComponentInfo
      description: Metadata associated with flowchem components.
    DeviceInfo:
      properties:
        manufacturer:
          type: string
          title: Manufacturer
          default: ''
        model:
          type: string
          title: Model
          default: ''
        version:
          type: string
          title: Version
          default: ''
        serial_number:
          anyOf:
          - type: string
          - type: integer
          title: Serial Number
          default: unknown
        components:
          additionalProperties:
            type: string
            minLength: 1
            format: uri
          type: object
          title: Components
          default: {}
        backend:
          type: string
          title: Backend
          default: flowchem v. 1.0.0a3
        authors:
          items:
            type: string
            format: name-email
          type: array
          title: Authors
          default: []
        additional_info:
          type: object
          title: Additional Info
          default: {}
      type: object
      title: DeviceInfo
      description: Metadata associated with hardware devices.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValveInfo:
      properties:
        ports:
          items:
            items: {}
            type: array
          type: array
          title: Ports
        positions:
          additionalProperties:
            items:
              items:
                anyOf:
                - type: integer
                - type: 'null'
              type: array
            type: array
          type: object
          title: Positions
      type: object
      required:
      - ports
      - positions
      title: ValveInfo
      description: "Model representing valve information.\n\nAttributes:\n    ports:\
        \ A list of tuples representing the available ports on the stator.\n    positions:\
        \ A dictionary mapping position numbers to the stator ports that are connected\
        \ at this position."
