[device.MFC]
type = "MFC"
port = " "
adress = 1
max_flow = 10

[device.Clarity]
type = "Clarity"
executable = "C:/claritychrom/bin/claritychrom.exe"
user = "admin"
password = ""
cfg_file = ""

[device.ML600]
type = "ML600"
port = " "
adress = 1
syringe_volume = '5 mL'

[device.EPC]
type = "EPC"
port = " "
adress = 2
max_flow = 10

[device.HuberChiller]
type = "HuberChiller"
port = " "

[device.AzuraCompact]
type = "AzuraCompact"
ip_address = "192.168.1.119"
max_pressure = "10 bar"

[device.KnauerValve]
type = "KnauerValve"
ip_address = "192.168.1.119"

[device.Spinsolve]
type = "Spinsolve"

[device.MansonPowerSupply]
type = "MansonPowerSupply"
port = " "

[device.PhidgetPowerSource5V]
type = "PhidgetPowerSource5V"
vint_serial_number = 627768
vint_hub_port = 3
vint_channel = 0

[device.PhidgetBubbleSensor]
type = "PhidgetBubbleSensor"
vint_serial_number = 627768
vint_hub_port = 0
vint_channel = 0

[device.PhidgetPressureSensor]
type = "PhidgetPressureSensor"
pressure_range = "0 bar, 25 bar"
vint_serial_number = 627768
vint_channel = 0

[device.CVC3000]
type = "CVC3000"
port = " "

[device.R4Heater]
type = "R4Heater"
port = " "

[device.R2]
type = "R2"
port = " "

[device.ViciValve]
type = "ViciValve"
port = " "
adress = 0

[device.IcIR]
type = "IcIR"
url = "opc.tcp://localhost:62552/iCOpcUaServer"
template = "30sec_2days.iCIRTemplate"

[device.my-plugin-device]
type = "plugins"

[device.my-magic-ear]
type = "ExtendableEar"