SPACE_GRID_FIG = 20

PATTERN_DIMENSION = 1

MIN_DISTANCE_TO_ACTIVATED = 1

MIN_DISTANCE_TO_MOVE = 1

LOCATION_NEW_DEVICES = (SPACE_GRID_FIG - MIN_DISTANCE_TO_ACTIVATED, SPACE_GRID_FIG - MIN_DISTANCE_TO_ACTIVATED)

ITENS_GROUPS = 'devices connections others'.split()