openapi: 3.1.0
info:
  title: 'Flowchem - '
  description: Flowchem is a library to control instruments and devices commonly found
    in chemistry labs via an interoperable web API.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0a3
paths:
  /my-mansonpower/:
    get:
      tags:
      - my-mansonpower
      summary: Get Device Info
      operationId: get_device_info_fake_device__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInfo'
  /my-mansonpower/power-control/:
    get:
      tags:
      - my-mansonpower
      - my-mansonpower
      summary: Get Component Info
      description: "Retrieve the component's metadata.\n\nThis endpoint provides information\
        \ about the component, such as its name and associated hardware device.\n\n\
        Returns:\n--------\nComponentInfo\n    Metadata about the component."
      operationId: get_component_info_fake_device_power_control__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentInfo'
  /my-mansonpower/power-control/power-on:
    put:
      tags:
      - my-mansonpower
      - my-mansonpower
      summary: Power On
      description: "Turn on the power supply output.\n\nReturns:\n    Awaitable: Result\
        \ of the power on operation from the hardware device."
      operationId: power_on_fake_device_power_control_power_on_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /my-mansonpower/power-control/power-off:
    put:
      tags:
      - my-mansonpower
      - my-mansonpower
      summary: Power Off
      description: "Turn off the power supply output.\n\nReturns:\n    Awaitable:\
        \ Result of the power off operation from the hardware device."
      operationId: power_off_fake_device_power_control_power_off_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /my-mansonpower/power-control/current:
    get:
      tags:
      - my-mansonpower
      - my-mansonpower
      summary: Get Current
      description: "Retrieve the current output in Amperes.\n\nReturns:\n    float:\
        \ The current output in Amperes."
      operationId: get_current_fake_device_power_control_current_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: number
                title: Response Get Current Fake Device Power Control Current Get
    put:
      tags:
      - my-mansonpower
      - my-mansonpower
      summary: Set Current
      description: "Set the target current using a natural language string.\n\nArgs:\n\
        \    current (str): The desired current as a string in natural language (e.g.,\
        \ '5A', '500mA').\n\nReturns:\n    Awaitable: Result of the set_current operation\
        \ from the hardware device."
      operationId: set_current_fake_device_power_control_current_put
      parameters:
      - name: current
        in: query
        required: true
        schema:
          type: string
          title: Current
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /my-mansonpower/power-control/voltage:
    get:
      tags:
      - my-mansonpower
      - my-mansonpower
      summary: Get Voltage
      description: "Retrieve the current output voltage in Volts.\n\nReturns:\n  \
        \  float: The current output voltage in Volts."
      operationId: get_voltage_fake_device_power_control_voltage_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: number
                title: Response Get Voltage Fake Device Power Control Voltage Get
    put:
      tags:
      - my-mansonpower
      - my-mansonpower
      summary: Set Voltage
      description: "Set the target voltage using a natural language string.\n\nArgs:\n\
        \    voltage (str): The desired voltage as a string in natural language (e.g.,\
        \ '12V', '3.3V').\n\nReturns:\n    Awaitable: Result of the set_voltage operation\
        \ from the hardware device."
      operationId: set_voltage_fake_device_power_control_voltage_put
      parameters:
      - name: voltage
        in: query
        required: true
        schema:
          type: string
          title: Voltage
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ComponentInfo:
      properties:
        name:
          type: string
          title: Name
          default: ''
        parent_device:
          type: string
          title: Parent Device
          default: ''
        type:
          type: string
          title: Type
          default: ''
        owl_subclass_of:
          items:
            type: string
          type: array
          title: Owl Subclass Of
          default:
          - http://purl.obolibrary.org/obo/OBI_0000968
      type: object
      title: ComponentInfo
      description: Metadata associated with flowchem components.
    DeviceInfo:
      properties:
        manufacturer:
          type: string
          title: Manufacturer
          default: ''
        model:
          type: string
          title: Model
          default: ''
        version:
          type: string
          title: Version
          default: ''
        serial_number:
          anyOf:
          - type: string
          - type: integer
          title: Serial Number
          default: unknown
        components:
          additionalProperties:
            type: string
            minLength: 1
            format: uri
          type: object
          title: Components
          default: {}
        backend:
          type: string
          title: Backend
          default: flowchem v. 1.0.0a3
        authors:
          items:
            type: string
            format: name-email
          type: array
          title: Authors
          default: []
        additional_info:
          type: object
          title: Additional Info
          default: {}
      type: object
      title: DeviceInfo
      description: Metadata associated with hardware devices.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
