[device.syr5]
address = 5
type = "Elite11"
port = "COM5"
syringe_diameter = "10.3 mm"
syringe_volume = "5 ml"

[device.6PortValve]
type = "KnauerValve"
mac_address = "00:80:a3:b4:ce:80"
network = "141.14.*.*"

[device.r2]
type = "R2"
port = "COM6"

